import { createFileRoute } from '@tanstack/react-router';
import { Check } from 'lucide-react';
import { ContactBand } from '@/components/site-shell';
export const Route = createFileRoute('/about')({
 head:()=>({meta:[{title:'About Flowline — A personal approach to plumbing'},{name:'description',content:'Meet the idea behind Flowline: local plumbing with clear communication and respect for your home in Karachi.'},{property:'og:title',content:'About Flowline — People before pipes'},{property:'og:description',content:'A thoughtful, local approach to caring for homes in Karachi.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),
 component:AboutPage,
});
function AboutPage(){return <>
 <section className="page-intro"><div className="container"><p className="eyebrow">ABOUT FLOWLINE</p><h1>Good work starts<br/>with good people.</h1><p>We’re here to make looking after your home a little simpler. A local plumbing team with a practical approach and a personal touch.</p></div></section>
 <section className="section"><div className="container"><div className="story-grid"><img className="story-photo" src="/images/plumber.jpg" alt="A plumber taking care with a kitchen faucet" width={1920} height={1024}/><div className="story-copy"><p className="eyebrow">PEOPLE BEFORE PIPES</p><h2>A home is more<br/>than an address.</h2><p>It’s where your day begins and where you come back to unwind. When something stops working, you need someone who understands both the problem and the disruption it brings.</p><p>At Flowline, our approach is straightforward: listen carefully, explain the options, and do the work with care. From the first conversation to the final check, your comfort matters.</p><ul className="check-list"><li><Check/>Straightforward conversations</li><li><Check/>Careful, considered solutions</li><li><Check/>Respect for your home and your day</li></ul></div></div><div className="values-grid"><div><p className="eyebrow">01 / CLARITY</p><h3>Know where you stand.</h3><p>We talk through the problem and the proposed work before getting started. You deserve to understand what happens next.</p></div><div><p className="eyebrow">02 / CARE</p><h3>The details matter.</h3><p>From protecting your surfaces to checking our work, we pay attention to the things that make a visit feel reassuring.</p></div><div><p className="eyebrow">03 / COMMUNITY</p><h3>Local feels different.</h3><p>Our focus is on homes in Karachi. We aim to be the familiar, approachable team you feel comfortable calling.</p></div></div></div></section>
 <ContactBand/>
 </>;}
